-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, CONCAT(A.CITY, ' ', A.STREET_ADDRESS1, ' ', A.STREET_ADDRESS2) 전체주소, CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) 전화번호
FROM USED_GOODS_USER A
JOIN (
SELECT WRITER_ID, count(*) count
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID) B
ON A.USER_ID = B.WRITER_ID
WHERE B.count >= 3
ORDER BY A.USER_ID DESC;