-- 코드를 입력하세요
SELECT mp.MEMBER_NAME, mr.REVIEW_TEXT, DATE_FORMAT(mr.REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW mr join MEMBER_PROFILE mp
ON mr.MEMBER_ID = mp.MEMBER_ID
where mp.MEMBER_ID =
(SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY(MEMBER_ID)
ORDER BY COUNT(*) DESC
LIMIT 1)
ORDER BY mr.REVIEW_DATE ASC, mr.REVIEW_TEXT ASC;

-- REST_REVIEW
-- MEMBER_PROFILE, REST_REVIEW 테이블에서 리뷰 가장 많이 작성한 회원의 리뷰들 조회