-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, B.S * A.PRICE TOTAL_SALES
FROM FOOD_PRODUCT A 
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) S
      FROM FOOD_ORDER 
      WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
      GROUP BY PRODUCT_ID
      ) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID;